# *** Override behavior of AtomsCityLocations.py ***
# -- Override ability: Incremental
# -- Levels: All
'''
    Description: Contains major and minor city locations to populate
    products

    @since: February 2025
    @author: GSL Hazard Services Team
'''

AtomsCityLocations = {
    "AkBcWc": {
        "major": {
            "Adak": {
                "name": "Adak",
                "lat": 51.902777,
                "lon":-176.699342,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Anchorage": {
                "name": "Anchorage",
                "lat": 61.200443,
                "lon":-149.902106,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Fairbanks": {
                "name": "Fairbanks",
                "lat": 64.801562,
                "lon":-147.701948,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Honolulu": {
                "name": "Honolulu",
                "lat": 21.322,
                "lon":-157.867,
                "state": "Hawaii",
                "state_abbrev": "HI",
                "country": "United States",
                },
            "Juneau": {
                "name": "Juneau",
                "lat": 58.299415,
                "lon":-134.397868,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Los Angeles": {
                "name": "Los Angeles",
                "lat": 34.057882,
                "lon":-118.251918,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Nome": {
                "name": "Nome",
                "lat": 64.499185,
                "lon":-165.400614,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Petropavlovsk-Kamchatskiy": {
                "name": "Petropavlovsk-Kamchatskiy",
                "lat": 53.01813,
                "lon": 158.652013,
                "state": "Kamchatka Krai",
                "state_abbrev": "KK",
                "country": "Russia",
                },
            "Portland": {
                "name": "Portland",
                "lat": 45.536896,
                "lon":-122.617856,
                "state": "Oregon",
                "state_abbrev": "OR",
                "country": "United States",
                },
            "Prince Rupert": {
                "name": "Prince Rupert",
                "lat": 54.317,
                "lon":-130.31,
                "state": "British Columbia",
                "state_abbrev": "BC",
                "country": "Canada",
                },
            "San Francisco": {
                "name": "San Francisco",
                "lat": 37.778535,
                "lon":-122.417321,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Seattle": {
                "name": "Seattle",
                "lat": 47.59883,
                "lon":-122.331377,
                "state": "Washington",
                "state_abbrev": "WA",
                "country": "United States",
                },
            },
        "minor": {
            "Amchitka": {
                "name": "Amchitka",
                "lat": 51.502325,
                "lon": 178.997745,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Amukta Pass": {
                "name": "Amukta Pass",
                "lat": 52.303193,
                "lon":-172.001088,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Arctic Village": {
                "name": "Arctic Village",
                "lat": 68.098135,
                "lon":-145.50179,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Atka Village": {
                "name": "Atka Village",
                "lat": 52.200232,
                "lon":-174.201246,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Attu Island": {
                "name": "Attu Island",
                "lat": 52.903748,
                "lon": 173.199412,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Bakersfield": {
                "name": "Bakersfield",
                "lat": 35.373094,
                "lon":-119.019681,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Barstow": {
                "name": "Barstow",
                "lat": 34.896446,
                "lon":-117.020058,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Barter Island": {
                "name": "Barter Island",
                "lat": 70.099151,
                "lon":-143.696973,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Bering Island": {
                "name": "Bering Island",
                "lat": 55.00219,
                "lon": 165.997332,
                "state": "Kamchatka Krai",
                "state_abbrev": "KK",
                "country": "Russia",
                },
            "Bethel": {
                "name": "Bethel",
                "lat": 60.800797,
                "lon":-161.80244,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Bettles": {
                "name": "Bettles",
                "lat": 66.900635,
                "lon":-151.701194,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Boise": {
                "name": "Boise",
                "lat": 43.611521,
                "lon":-116.217917,
                "state": "Idaho",
                "state_abbrev": "ID",
                "country": "United States",
                },
            "Buldir Island": {
                "name": "Buldir Island",
                "lat": 52.303193,
                "lon": 175.898043,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Burwash Landing": {
                "name": "Burwash Landing",
                "lat": 61.303204,
                "lon":-138.998719,
                "state": "Yukon",
                "state_abbrev": "YU",
                "country": "Canada",
                },
            "Cape Newenham": {
                "name": "Cape Newenham",
                "lat": 58.699267,
                "lon":-162.19778,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Cape Yakataga": {
                "name": "Cape Yakataga",
                "lat": 60.087063,
                "lon":-142.402089,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Chignik": {
                "name": "Chignik",
                "lat": 56.299647,
                "lon":-158.39907,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Cold Bay": {
                "name": "Cold Bay",
                "lat": 55.202263,
                "lon":-162.701983,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Cordova": {
                "name": "Cordova",
                "lat": 60.498186,
                "lon":-145.799728,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Dawson City": {
                "name": "Dawson City",
                "lat": 64.099793,
                "lon":-139.302387,
                "state": "Yukon",
                "state_abbrev": "YU",
                "country": "Canada",
                },
            "Denali Park": {
                "name": "Denali Park",
                "lat": 63.700372,
                "lon":-148.89943,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Dillingham": {
                "name": "Dillingham",
                "lat": 59.001989,
                "lon":-158.502203,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Dixon Entrance": {
                "name": "Dixon Entrance",
                "lat": 54.499112,
                "lon":-132.999851,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Dutch Harbor": {
                "name": "Dutch Harbor",
                "lat": 53.898773,
                "lon":-166.500693,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "El Centro": {
                "name": "El Centro",
                "lat": 32.794004,
                "lon":-115.559016,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Eugene": {
                "name": "Eugene",
                "lat": 44.081485,
                "lon":-123.070493,
                "state": "Oregon",
                "state_abbrev": "OR",
                "country": "United States",
                },
            "Eureka": {
                "name": "Eureka",
                "lat": 40.784916,
                "lon":-124.159112,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Fort Yukon": {
                "name": "Fort Yukon",
                "lat": 66.59837,
                "lon":-145.301255,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Fresno": {
                "name": "Fresno",
                "lat": 36.733849,
                "lon":-119.781715,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Haines": {
                "name": "Haines",
                "lat": 59.201889,
                "lon":-135.400544,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Hilo": {
                "name": "Hilo",
                "lat": 19.735,
                "lon":-155.082,
                "state": "Hawaii",
                "state_abbrev": "HI",
                "country": "United States",
                },
            "Holy Cross": {
                "name": "Holy Cross",
                "lat": 62.199418,
                "lon":-159.802817,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Homer": {
                "name": "Homer",
                "lat": 59.601665,
                "lon":-151.500658,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Iliamna": {
                "name": "Iliamna",
                "lat": 59.801541,
                "lon":-154.898298,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Kahului": {
                "name": "Kahului",
                "lat": 20.893,
                "lon":-156.468,
                "state": "Hawaii",
                "state_abbrev": "HI",
                "country": "United States",
                },
            "Ketchikan": {
                "name": "Ketchikan",
                "lat": 55.299438,
                "lon":-131.601834,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "King Salmon": {
                "name": "King Salmon",
                "lat": 58.699267,
                "lon":-156.697386,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Klamath Falls": {
                "name": "Klamath Falls",
                "lat": 42.224253,
                "lon":-121.769878,
                "state": "Oregon",
                "state_abbrev": "OR",
                "country": "United States",
                },
            "Kobuk": {
                "name": "Kobuk",
                "lat": 66.900635,
                "lon":-156.897921,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Kodiak City": {
                "name": "Kodiak City",
                "lat": 57.80241,
                "lon":-152.4072,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Kotzebue": {
                "name": "Kotzebue",
                "lat": 66.900635,
                "lon":-162.598851,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Lake Minchumina": {
                "name": "Lake Minchumina",
                "lat": 63.900086,
                "lon":-152.29707,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Las Vegas": {
                "name": "Las Vegas",
                "lat": 36.171225,
                "lon":-115.146486,
                "state": "Nevada",
                "state_abbrev": "NV",
                "country": "United States",
                },
            "Lime Village": {
                "name": "Lime Village",
                "lat": 61.400254,
                "lon":-155.499904,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Mccarthy": {
                "name": "Mccarthy",
                "lat": 61.400254,
                "lon":-142.900562,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Mcgrath": {
                "name": "Mcgrath",
                "lat": 62.998459,
                "lon":-155.597307,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Monterey": {
                "name": "Monterey",
                "lat": 36.619034,
                "lon":-121.913118,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Nawiliwili": {
                "name": "Nawiliwili",
                "lat": 21.957,
                "lon":-159.36,
                "state": "Hawaii",
                "state_abbrev": "HI",
                "country": "United States",
                },
            "Needles": {
                "name": "Needles",
                "lat": 34.844758,
                "lon":-114.613636,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Nikolski": {
                "name": "Nikolski",
                "lat": 52.903748,
                "lon":-168.901387,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Nunivak Island": {
                "name": "Nunivak Island",
                "lat": 60.001408,
                "lon":-166.00222,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Old Crow": {
                "name": "Old Crow",
                "lat": 67.56666,
                "lon":-139.8,
                "state": "Yukon",
                "state_abbrev": "YU",
                "country": "Canada",
                },
            "Palmer": {
                "name": "Palmer",
                "lat": 61.600057,
                "lon":-149.099965,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Point Lay": {
                "name": "Point Lay",
                "lat": 69.802744,
                "lon":-162.999921,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Port Alice": {
                "name": "Port Alice",
                "lat": 50.203461,
                "lon":-127.201518,
                "state": "British Columbia",
                "state_abbrev": "BC",
                "country": "Canada",
                },
            "Pribilof Islands": {
                "name": "Pribilof Islands",
                "lat": 57.13,
                "lon":-170.28,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Prudhoe Bay": {
                "name": "Prudhoe Bay",
                "lat": 70.401245,
                "lon":-148.400957,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Reno": {
                "name": "Reno",
                "lat": 39.522948,
                "lon":-119.804633,
                "state": "Nevada",
                "state_abbrev": "NV",
                "country": "United States",
                },
            "Sacramento": {
                "name": "Sacramento",
                "lat": 38.639352,
                "lon":-121.489129,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Salt Lake City": {
                "name": "Salt Lake City",
                "lat": 40.756239,
                "lon":-111.880627,
                "state": "Utah",
                "state_abbrev": "UT",
                "country": "United States",
                },
            "San Diego": {
                "name": "San Diego",
                "lat": 32.713563,
                "lon":-117.151839,
                "state": "California",
                "state_abbrev": "CA",
                "country": "United States",
                },
            "Sand Point": {
                "name": "Sand Point",
                "lat": 55.299438,
                "lon":-160.501825,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Sandspit": {
                "name": "Sandspit",
                "lat": 53.241166,
                "lon":-131.842476,
                "state": "British Columbia",
                "state_abbrev": "BC",
                "country": "Canada",
                },
            "Seward": {
                "name": "Seward",
                "lat": 60.098484,
                "lon":-149.397903,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Shemya Island": {
                "name": "Shemya Island",
                "lat": 52.697852,
                "lon": 174.098956,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Sitka": {
                "name": "Sitka",
                "lat": 57.099658,
                "lon":-135.297412,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Spokane": {
                "name": "Spokane",
                "lat": 47.67327,
                "lon":-117.40394,
                "state": "Washington",
                "state_abbrev": "WA",
                "country": "United States",
                },
            "St. Matthew Island": {
                "name": "St. Matthew Island",
                "lat": 60.401119,
                "lon":-172.700097,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Talkeetna": {
                "name": "Talkeetna",
                "lat": 62.302159,
                "lon":-150.096912,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Tanana": {
                "name": "Tanana",
                "lat": 65.200903,
                "lon":-152.102264,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Tok": {
                "name": "Tok",
                "lat": 63.300921,
                "lon":-142.997965,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Tonopah": {
                "name": "Tonopah",
                "lat": 38.071232,
                "lon":-117.226323,
                "state": "Nevada",
                "state_abbrev": "NV",
                "country": "United States",
                },
            "Umiat": {
                "name": "Umiat",
                "lat": 69.398012,
                "lon":-152.102264,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Unalakleet": {
                "name": "Unalakleet",
                "lat": 63.900086,
                "lon":-160.799763,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Valdez": {
                "name": "Valdez",
                "lat": 61.09768,
                "lon":-146.298202,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Whitehorse": {
                "name": "Whitehorse",
                "lat": 60.703735,
                "lon":-135.096877,
                "state": "Yukon",
                "state_abbrev": "YU",
                "country": "Canada",
                },
            "Wiseman": {
                "name": "Wiseman",
                "lat": 67.402473,
                "lon":-150.096912,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            "Yakutat": {
                "name": "Yakutat",
                "lat": 59.601665,
                "lon":-139.697728,
                "state": "Alaska",
                "state_abbrev": "AK",
                "country": "United States",
                },
            },
        },
    "EcGc": {
        "major": {
            "Bangor": {
                "name": "Bangor",
                "lat": 44.8,
                "lon":-68.79,
                "state": "Maine",
                "state_abbrev": "ME",
                "country": "United States",
                },
            "Boston": {
                "name": "Boston",
                "lat": 42.37,
                "lon":-71.03,
                "state": "Massachusetts",
                "state_abbrev": "MA",
                "country": "United States",
                },
            "Charleston": {
                "name": "Charleston",
                "lat": 32.78,
                "lon":-79.93,
                "state": "South Carolina",
                "state_abbrev": "SC",
                "country": "United States",
                },
            "Houston": {
                "name": "Houston",
                "lat": 29.77,
                "lon":-95.35,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Jacksonville": {
                "name": "Jacksonville",
                "lat": 30.33,
                "lon":-81.65,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Miami": {
                "name": "Miami",
                "lat": 25.77,
                "lon":-80.18,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Mobile": {
                "name": "Mobile",
                "lat": 30.68,
                "lon":-88.03,
                "state": "Alabama",
                "state_abbrev": "AL",
                "country": "United States",
                },
            "New Orleans": {
                "name": "New Orleans",
                "lat": 29.95,
                "lon":-90.07,
                "state": "Louisiana",
                "state_abbrev": "LA",
                "country": "United States",
                },
            "New York": {
                "name": "New York",
                "lat": 40.77,
                "lon":-73.98,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Norfolk": {
                "name": "Norfolk",
                "lat": 36.85,
                "lon":-76.28,
                "state": "Virginia",
                "state_abbrev": "VA",
                "country": "United States",
                },
            "Philadelphia": {
                "name": "Philadelphia",
                "lat": 39.95,
                "lon":-75.15,
                "state": "Pennsylvania",
                "state_abbrev": "PA",
                "country": "United States",
                },
            "Richmond": {
                "name": "Richmond",
                "lat": 37.55,
                "lon":-77.43,
                "state": "Virginia",
                "state_abbrev": "VA",
                "country": "United States",
                },
            "San Juan": {
                "name": "San Juan",
                "lat": 18.45,
                "lon":-66.1,
                "state": "Puerto Rico",
                "state_abbrev": "PR",
                "country": "United States",
                },
            "Savannah": {
                "name": "Savannah",
                "lat": 32.08,
                "lon":-81.1,
                "state": "Georgia",
                "state_abbrev": "GA",
                "country": "United States",
                },
            "Tampa": {
                "name": "Tampa",
                "lat": 27.95,
                "lon":-82.47,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Washington": {
                "name": "Washington",
                "lat": 38.85,
                "lon":-77.04,
                "state": "District of Columbia",
                "state_abbrev": "DC",
                "country": "United States",
                },
            "Wilmington": {
                "name": "Wilmington",
                "lat": 34.22,
                "lon":-77.92,
                "state": "North Carolina",
                "state_abbrev": "NC",
                "country": "United States",
                },
            },
        "minor": {
            "Abilene": {
                "name": "Abilene",
                "lat": 32.45,
                "lon":-99.73,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Albany": {
                "name": "Albany",
                "lat": 31.58,
                "lon":-84.15,
                "state": "Georgia",
                "state_abbrev": "GA",
                "country": "United States",
                },
            "Alexandria": {
                "name": "Alexandria",
                "lat": 31.32,
                "lon":-92.45,
                "state": "Louisiana",
                "state_abbrev": "LA",
                "country": "United States",
                },
            "Allentown": {
                "name": "Allentown",
                "lat": 40.65,
                "lon":-75.5,
                "state": "Pennsylvania",
                "state_abbrev": "PA",
                "country": "United States",
                },
            "Amarillo": {
                "name": "Amarillo",
                "lat": 35.23,
                "lon":-101.83,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Apalachicola": {
                "name": "Apalachicola",
                "lat": 29.73,
                "lon":-84.98,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Asheville": {
                "name": "Asheville",
                "lat": 35.6,
                "lon":-82.55,
                "state": "North Carolina",
                "state_abbrev": "NC",
                "country": "United States",
                },
            "Atlanta": {
                "name": "Atlanta",
                "lat": 33.75,
                "lon":-84.4,
                "state": "Georgia",
                "state_abbrev": "GA",
                "country": "United States",
                },
            "Atlantic City": {
                "name": "Atlantic City",
                "lat": 39.35,
                "lon":-74.42,
                "state": "New Jersey",
                "state_abbrev": "NJ",
                "country": "United States",
                },
            "Augusta": {
                "name": "Augusta",
                "lat": 44.32,
                "lon":-69.8,
                "state": "Maine",
                "state_abbrev": "ME",
                "country": "United States",
                },
            "Austin": {
                "name": "Austin",
                "lat": 30.27,
                "lon":-97.75,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Bar Harbor": {
                "name": "Bar Harbor",
                "lat": 44.38,
                "lon":-68.2,
                "state": "Maine",
                "state_abbrev": "ME",
                "country": "United States",
                },
            "Baton Rouge": {
                "name": "Baton Rouge",
                "lat": 30.45,
                "lon":-91.15,
                "state": "Louisiana",
                "state_abbrev": "LA",
                "country": "United States",
                },
            "Binghamton": {
                "name": "Binghamton",
                "lat": 42.1,
                "lon":-75.9,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Birmingham": {
                "name": "Birmingham",
                "lat": 33.51,
                "lon":-86.8,
                "state": "Alabama",
                "state_abbrev": "AL",
                "country": "United States",
                },
            "Bradford": {
                "name": "Bradford",
                "lat": 41.95,
                "lon":-78.63,
                "state": "Pennsylvania",
                "state_abbrev": "PA",
                "country": "United States",
                },
            "Brownsville": {
                "name": "Brownsville",
                "lat": 25.9,
                "lon":-97.45,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Buffalo": {
                "name": "Buffalo",
                "lat": 42.88,
                "lon":-78.85,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Cape Canaveral": {
                "name": "Cape Canaveral",
                "lat": 28.47,
                "lon":-80.55,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Cape Chidley": {
                "name": "Cape Chidley",
                "lat": 60.22,
                "lon":-64.84,
                "state": "Newfoundland and Labrador",
                "state_abbrev": "NL",
                "country": "Canada",
                },
            "Cape Hatteras": {
                "name": "Cape Hatteras",
                "lat": 35.22,
                "lon":-75.55,
                "state": "North Carolina",
                "state_abbrev": "NC",
                "country": "United States",
                },
            "Charlotte Amalie": {
                "name": "Charlotte Amalie",
                "lat": 18.335,
                "lon":-64.92,
                "state": "St. Thomas",
                "state_abbrev": "VI",
                "country": "United States",
                },
            "Charlottetown": {
                "name": "Charlottetown",
                "lat": 46.23,
                "lon":-63.13,
                "state": "Prince Edward Island",
                "state_abbrev": "PE",
                "country": "Canada",
                },
            "Chicago": {
                "name": "Chicago",
                "lat": 41.88,
                "lon":-87.63,
                "state": "Illinois",
                "state_abbrev": "IL",
                "country": "United States",
                },
            "Christiansted": {
                "name": "Christiansted",
                "lat": 17.768,
                "lon":-64.695,
                "state": "St. Croix",
                "state_abbrev": "VI",
                "country": "United States",
                },
            "Cleveland": {
                "name": "Cleveland",
                "lat": 41.5,
                "lon":-81.7,
                "state": "Ohio",
                "state_abbrev": "OH",
                "country": "United States",
                },
            "Columbia": {
                "name": "Columbia",
                "lat": 33.95,
                "lon":-81.12,
                "state": "South Carolina",
                "state_abbrev": "SC",
                "country": "United States",
                },
            "Columbus": {
                "name": "Columbus",
                "lat": 39.97,
                "lon":-83.0,
                "state": "Ohio",
                "state_abbrev": "OH",
                "country": "United States",
                },
            "Concord": {
                "name": "Concord",
                "lat": 43.2,
                "lon":-71.5,
                "state": "New Hampshire",
                "state_abbrev": "NH",
                "country": "United States",
                },
            "Corpus Christi": {
                "name": "Corpus Christi",
                "lat": 27.8,
                "lon":-97.4,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Cumberland": {
                "name": "Cumberland",
                "lat": 39.65,
                "lon":-78.77,
                "state": "Maryland",
                "state_abbrev": "MD",
                "country": "United States",
                },
            "Dalhousie": {
                "name": "Dalhousie",
                "lat": 48.07,
                "lon":-66.37,
                "state": "New Brunswick",
                "state_abbrev": "NB",
                "country": "Canada",
                },
            "Dallas": {
                "name": "Dallas",
                "lat": 32.78,
                "lon":-96.8,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Dansville": {
                "name": "Dansville",
                "lat": 42.57,
                "lon":-77.7,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Del Rio": {
                "name": "Del Rio",
                "lat": 29.37,
                "lon":-100.9,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Detroit": {
                "name": "Detroit",
                "lat": 42.33,
                "lon":-82.95,
                "state": "Michigan",
                "state_abbrev": "MI",
                "country": "United States",
                },
            "Dover": {
                "name": "Dover",
                "lat": 39.15,
                "lon":-75.52,
                "state": "Delaware",
                "state_abbrev": "DE",
                "country": "United States",
                },
            "El Paso": {
                "name": "El Paso",
                "lat": 31.76,
                "lon":-106.48,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Erie": {
                "name": "Erie",
                "lat": 42.13,
                "lon":-80.08,
                "state": "Pennsylvania",
                "state_abbrev": "PA",
                "country": "United States",
                },
            "Evansville": {
                "name": "Evansville",
                "lat": 37.97,
                "lon":-87.55,
                "state": "Indiana",
                "state_abbrev": "IN",
                "country": "United States",
                },
            "Fajardo": {
                "name": "Fajardo",
                "lat": 18.324,
                "lon":-65.645,
                "state": "Puerto Rico",
                "state_abbrev": "PR",
                "country": "United States",
                },
            "Fort Bragg": {
                "name": "Fort Bragg",
                "lat": 35.13,
                "lon":-78.93,
                "state": "North Carolina",
                "state_abbrev": "NC",
                "country": "United States",
                },
            "Gainesville": {
                "name": "Gainesville",
                "lat": 29.68,
                "lon":-82.27,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Galveston": {
                "name": "Galveston",
                "lat": 29.3,
                "lon":-94.8,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Grand Isle": {
                "name": "Grand Isle",
                "lat": 29.23,
                "lon":-89.98,
                "state": "Louisiana",
                "state_abbrev": "LA",
                "country": "United States",
                },
            "Greensboro": {
                "name": "Greensboro",
                "lat": 36.08,
                "lon":-79.79,
                "state": "North Carolina",
                "state_abbrev": "NC",
                "country": "United States",
                },
            "Greenville": {
                "name": "Greenville",
                "lat": 33.48,
                "lon":-90.98,
                "state": "Mississippi",
                "state_abbrev": "MS",
                "country": "United States",
                },
            "Halifax": {
                "name": "Halifax",
                "lat": 44.67,
                "lon":-63.58,
                "state": "Nova Scotia",
                "state_abbrev": "NS",
                "country": "Canada",
                },
            "Hopedale": {
                "name": "Hopedale",
                "lat": 55.47,
                "lon":-60.22,
                "state": "Newfoundland and Labrador",
                "state_abbrev": "NL",
                "country": "Canada",
                },
            "Huntsville": {
                "name": "Huntsville",
                "lat": 34.73,
                "lon":-86.58,
                "state": "Alabama",
                "state_abbrev": "AL",
                "country": "United States",
                },
            "Indianapolis": {
                "name": "Indianapolis",
                "lat": 39.77,
                "lon":-86.15,
                "state": "Indiana",
                "state_abbrev": "IN",
                "country": "United States",
                },
            "Jackson": {
                "name": "Jackson",
                "lat": 32.32,
                "lon":-90.18,
                "state": "Mississippi",
                "state_abbrev": "MS",
                "country": "United States",
                },
            "Kansas City": {
                "name": "Kansas City",
                "lat": 39.1,
                "lon":-94.58,
                "state": "Missouri",
                "state_abbrev": "MO",
                "country": "United States",
                },
            "Key West": {
                "name": "Key West",
                "lat": 24.55,
                "lon":-81.78,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "L'Anse Au Clair": {
                "name": "L'Anse Au Clair",
                "lat": 51.41,
                "lon":-57.11,
                "state": "Newfoundland and Labrador",
                "state_abbrev": "NL",
                "country": "Canada",
                },
            "Lake Charles": {
                "name": "Lake Charles",
                "lat": 30.23,
                "lon":-93.22,
                "state": "Louisiana",
                "state_abbrev": "LA",
                "country": "United States",
                },
            "Lancaster": {
                "name": "Lancaster",
                "lat": 40.03,
                "lon":-76.3,
                "state": "Pennsylvania",
                "state_abbrev": "PA",
                "country": "United States",
                },
            "Laredo": {
                "name": "Laredo",
                "lat": 27.5,
                "lon":-99.5,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Lebanon": {
                "name": "Lebanon",
                "lat": 43.63,
                "lon":-72.3,
                "state": "New Hampshire",
                "state_abbrev": "NH",
                "country": "United States",
                },
            "Lexington": {
                "name": "Lexington",
                "lat": 37.98,
                "lon":-84.48,
                "state": "Kentucky",
                "state_abbrev": "KY",
                "country": "United States",
                },
            "Little Rock": {
                "name": "Little Rock",
                "lat": 34.75,
                "lon":-92.28,
                "state": "Arkansas",
                "state_abbrev": "AR",
                "country": "United States",
                },
            "Lubbock": {
                "name": "Lubbock",
                "lat": 33.58,
                "lon":-101.85,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Lynchburg": {
                "name": "Lynchburg",
                "lat": 37.42,
                "lon":-79.15,
                "state": "Virginia",
                "state_abbrev": "VA",
                "country": "United States",
                },
            "Massena": {
                "name": "Massena",
                "lat": 44.93,
                "lon":-74.85,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Mayagüez": {
                "name": "Mayagüez",
                "lat": 18.2,
                "lon":-67.13,
                "state": "Puerto Rico",
                "state_abbrev": "PR",
                "country": "United States",
                },
            "Midland": {
                "name": "Midland",
                "lat": 32.0,
                "lon":-102.08,
                "state": "Texas",
                "state_abbrev": "TX",
                "country": "United States",
                },
            "Minneapolis": {
                "name": "Minneapolis",
                "lat": 44.98,
                "lon":-93.27,
                "state": "Minnesota",
                "state_abbrev": "MN",
                "country": "United States",
                },
            "Moncton": {
                "name": "Moncton",
                "lat": 46.08,
                "lon":-64.77,
                "state": "Nova Scotia",
                "state_abbrev": "NS",
                "country": "Canada",
                },
            "Montauk": {
                "name": "Montauk",
                "lat": 41.03,
                "lon":-71.95,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Montgomery": {
                "name": "Montgomery",
                "lat": 32.37,
                "lon":-86.35,
                "state": "Alabama",
                "state_abbrev": "AL",
                "country": "United States",
                },
            "Montpelier": {
                "name": "Montpelier",
                "lat": 44.2,
                "lon":-72.57,
                "state": "Vermont",
                "state_abbrev": "VT",
                "country": "United States",
                },
            "Montreal": {
                "name": "Montreal",
                "lat": 45.5,
                "lon":-73.58,
                "state": "Quebec",
                "state_abbrev": "QC",
                "country": "Canada",
                },
            "Moosonee": {
                "name": "Moosonee",
                "lat": 51.27,
                "lon":-80.65,
                "state": "Ontario",
                "state_abbrev": "ON",
                "country": "Canada",
                },
            "Myrtle Beach": {
                "name": "Myrtle Beach",
                "lat": 33.68,
                "lon":-78.9,
                "state": "South Carolina",
                "state_abbrev": "SC",
                "country": "United States",
                },
            "Nantucket": {
                "name": "Nantucket",
                "lat": 41.28,
                "lon":-70.17,
                "state": "Massachusetts",
                "state_abbrev": "MA",
                "country": "United States",
                },
            "Nashville": {
                "name": "Nashville",
                "lat": 36.17,
                "lon":-86.78,
                "state": "Tennessee",
                "state_abbrev": "TN",
                "country": "United States",
                },
            "New Haven": {
                "name": "New Haven",
                "lat": 41.3,
                "lon":-72.92,
                "state": "Connecticut",
                "state_abbrev": "CT",
                "country": "United States",
                },
            "Ocean City": {
                "name": "Ocean City",
                "lat": 38.33,
                "lon":-75.12,
                "state": "Maryland",
                "state_abbrev": "MD",
                "country": "United States",
                },
            "Ogdensburg": {
                "name": "Ogdensburg",
                "lat": 44.68,
                "lon":-75.45,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Oklahoma City": {
                "name": "Oklahoma City",
                "lat": 35.47,
                "lon":-97.52,
                "state": "Oklahoma",
                "state_abbrev": "OK",
                "country": "United States",
                },
            "Orlando": {
                "name": "Orlando",
                "lat": 28.53,
                "lon":-81.38,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Ottawa": {
                "name": "Ottawa",
                "lat": 45.42,
                "lon":-75.7,
                "state": "Ontario",
                "state_abbrev": "ON",
                "country": "Canada",
                },
            "Oxford": {
                "name": "Oxford",
                "lat": 34.39,
                "lon":-89.54,
                "state": "Mississippi",
                "state_abbrev": "MS",
                "country": "United States",
                },
            "Pensacola": {
                "name": "Pensacola",
                "lat": 30.41,
                "lon":-87.22,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Pittsburgh": {
                "name": "Pittsburgh",
                "lat": 41.43,
                "lon":-79.97,
                "state": "Pennsylvania",
                "state_abbrev": "PA",
                "country": "United States",
                },
            "Plattsburgh": {
                "name": "Plattsburgh",
                "lat": 44.65,
                "lon":-73.47,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Port aux Basques": {
                "name": "Port aux Basques",
                "lat": 47.57,
                "lon":-59.13,
                "state": "Newfoundland and Labrador",
                "state_abbrev": "NL",
                "country": "Canada",
                },
            "Portland": {
                "name": "Portland",
                "lat": 43.65,
                "lon":-70.32,
                "state": "Maine",
                "state_abbrev": "ME",
                "country": "United States",
                },
            "Presque Isle": {
                "name": "Presque Isle",
                "lat": 46.68,
                "lon":-67.98,
                "state": "Maine",
                "state_abbrev": "ME",
                "country": "United States",
                },
            "Providence": {
                "name": "Providence",
                "lat": 41.81,
                "lon":-71.4,
                "state": "Rhode Island",
                "state_abbrev": "RI",
                "country": "United States",
                },
            "Quebec": {
                "name": "Quebec",
                "lat": 46.8,
                "lon":-71.25,
                "state": "Quebec",
                "state_abbrev": "QC",
                "country": "Canada",
                },
            "Road Town": {
                "name": "Road Town",
                "lat": 18.438,
                "lon":-64.655,
                "state": "British Virgin Islands",
                "state_abbrev": "BVI",
                "country": "United States",
                },
            "Rochester": {
                "name": "Rochester",
                "lat": 43.17,
                "lon":-77.6,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Rockland": {
                "name": "Rockland",
                "lat": 44.1,
                "lon":-69.12,
                "state": "Maine",
                "state_abbrev": "ME",
                "country": "United States",
                },
            "Rumford": {
                "name": "Rumford",
                "lat": 44.55,
                "lon":-70.55,
                "state": "Maine",
                "state_abbrev": "ME",
                "country": "United States",
                },
            "Schenectady": {
                "name": "Schenectady",
                "lat": 42.82,
                "lon":-73.93,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Sept-Iles": {
                "name": "Sept-Iles",
                "lat": 50.2,
                "lon":-66.38,
                "state": "Quebec",
                "state_abbrev": "QC",
                "country": "Canada",
                },
            "Settlement": {
                "name": "Settlement",
                "lat": 18.724,
                "lon":-64.323,
                "state": "British Virgin Islands",
                "state_abbrev": "BVI",
                "country": "United States",
                },
            "Shreveport": {
                "name": "Shreveport",
                "lat": 32.52,
                "lon":-93.82,
                "state": "Louisiana",
                "state_abbrev": "LA",
                "country": "United States",
                },
            "Sioux City": {
                "name": "Sioux City",
                "lat": 42.5,
                "lon":-96.4,
                "state": "Iowa",
                "state_abbrev": "IA",
                "country": "United States",
                },
            "Springfield": {
                "name": "Springfield",
                "lat": 42.12,
                "lon":-72.6,
                "state": "Massachusetts",
                "state_abbrev": "MA",
                "country": "United States",
                },
            "St. Johns": {
                "name": "St. Johns",
                "lat": 47.57,
                "lon":-52.72,
                "state": "Newfoundland and Labrador",
                "state_abbrev": "NL",
                "country": "Canada",
                },
            "St. Louis": {
                "name": "St. Louis",
                "lat": 38.63,
                "lon":-90.2,
                "state": "Missouri",
                "state_abbrev": "MO",
                "country": "United States",
                },
            "State College": {
                "name": "State College",
                "lat": 40.78,
                "lon":-77.86,
                "state": "Pennsylvania",
                "state_abbrev": "PA",
                "country": "United States",
                },
            "Sydney": {
                "name": "Sydney",
                "lat": 46.22,
                "lon":-60.25,
                "state": "Nova Scotia",
                "state_abbrev": "NS",
                "country": "Canada",
                },
            "Syracuse": {
                "name": "Syracuse",
                "lat": 43.08,
                "lon":-76.12,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Tallahassee": {
                "name": "Tallahassee",
                "lat": 30.43,
                "lon":-84.28,
                "state": "Florida",
                "state_abbrev": "FL",
                "country": "United States",
                },
            "Toronto": {
                "name": "Toronto",
                "lat": 43.67,
                "lon":-79.42,
                "state": "Ontario",
                "state_abbrev": "ON",
                "country": "Canada",
                },
            "Utica": {
                "name": "Utica",
                "lat": 43.1,
                "lon":-75.25,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Val-d'Or": {
                "name": "Val-d'Or",
                "lat": 48.1,
                "lon":-77.78,
                "state": "Quebec",
                "state_abbrev": "QC",
                "country": "Canada",
                },
            "Watertown": {
                "name": "Watertown",
                "lat": 43.97,
                "lon":-75.9,
                "state": "New York",
                "state_abbrev": "NY",
                "country": "United States",
                },
            "Yarmouth": {
                "name": "Yarmouth",
                "lat": 43.83,
                "lon":-66.12,
                "state": "Nova Scotia",
                "state_abbrev": "NS",
                "country": "Canada",
                },
            },
        },
    }
