# *** Override behavior of AtomsProductLocationInfo.py ***
# -- Override ability: Incremental
# -- Levels: All
AtomsProductLocationInfo = {
    "The Cal./Mexico Border to Orange/San Diego Line": {
        "breakPointNumber": 0,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Orange/San Diego Line to Rincon Point": {
        "breakPointNumber": 1,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Rincon Point to Point Conception": {
        "breakPointNumber": 2,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Point Conception to Ragged Point": {
        "breakPointNumber": 3,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Ragged Point to Davenport": {
        "breakPointNumber": 4,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Davenport to Gualala River": {
        "breakPointNumber": 5,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {
            "San Francisco Bay": False,
            "Suisun Bay": False,
            },
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Gualala River to Mendo/Hum County Line": {
        "breakPointNumber": 6,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Mendo/Hum County Line to Cape Mendocino": {
        "breakPointNumber": 7,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Cape Mendocino to Humboldt/Del Norte Line": {
        "breakPointNumber": 8,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "Humboldt/Del Norte Line to The Oregon/Cal. Border": {
        "breakPointNumber": 9,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["California"],
        "subregion": "California",
    },
    "The Oregon/Cal. Border to Douglas/Lane Line": {
        "breakPointNumber": 10,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Oregon"],
        "subregion": "Oregon",
    },
    "Douglas/Lane Line to Cascade Head": {
        "breakPointNumber": 11,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Oregon"],
        "subregion": "Oregon",
    },
    "Cascade Head to The Oregon/Wash. Border": {
        "breakPointNumber": 12,
        "inclusionReferencePoints": {"Columbia River Estuary": True},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Oregon"],
        "subregion": "Oregon",
    },
    "The Oregon/Wash. Border to The Wash./BC Border": {
        "breakPointNumber": 13,
        "inclusionReferencePoints": {
            "Columbia River Estuary": True,
            "Cape Flattery": True,
            },
        "inclusionSpecialProcedures": {
            "Grays Bay": False,
            "Puget Sound": False,
            "Island County": True,
            "Possession Sound": True,
            "Southern Strait of Juan de Fuca": True,
            "Northern Strait of Juan de Fuca": False,
            "Western Skagit and Northwestern Snohomish Counties": True,
            "San Juan Islands": True,
            "Western Whatcom County": True,
            "Strait of Georgia": False,
            },
        "special": False,
        "states": ["Washington"],
        "subregion": "Washington",
    },
    "The Wash./BC Border to North Vancouver Island": {
        "breakPointNumber": 14,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {"Northern Strait of Juan de Fuca": True},
        "special": False,
        "states": ["British Columbia"],
        "subregion": "British Columbia",
    },
    "North Vancouver Island to The BC/Alaska Border": {
        "breakPointNumber": 15,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["British Columbia"],
        "subregion": "British Columbia",
    },
    "The BC/Alaska Border to Cape Decision": {
        "breakPointNumber": 16,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "Southeast Alaska",
    },
    "Cape Decision to Salisbury Sound": {
        "breakPointNumber": 17,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "Southeast Alaska",
    },
    "Salisbury Sound to Cape Fairweather": {
        "breakPointNumber": 18,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "Southeast Alaska",
    },
    "Cape Fairweather to Cape Suckling": {
        "breakPointNumber": 19,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "South Alaska and the Alaska Peninsula",
    },
    "Cape Suckling to Hinchinbrook Entrance": {
        "breakPointNumber": 20,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "South Alaska and the Alaska Peninsula",
    },
    "Hinchinbrook Entrance to Kennedy Entrance": {
        "breakPointNumber": 21,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {
            "Lower Cook Inlet Region south of Kalgin Island": True,
            "Northwest Kenai Peninsula": True,
            "Upper Cook Inlet": False,
            },

        "special": False,
        "states": ["Alaska"],
        "subregion": "South Alaska and the Alaska Peninsula",
    },
    "Kennedy Entrance to Chignik Bay": {
        "breakPointNumber": 22,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {
            "Lower Cook Inlet Region south of Kalgin Island": False,
            "Northwest Kenai Peninsula": False,
            "Upper Cook Inlet": False,
            },
        "special": False,
        "states": ["Alaska"],
        "subregion": "South Alaska and the Alaska Peninsula",
    },
    "Chignik Bay to Unimak Pass": {
        "breakPointNumber": 23,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "South Alaska and the Alaska Peninsula",
    },
    "Unimak Pass to Samalga Pass": {
        "breakPointNumber": 24,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "Aleutian Islands",
    },
    "Samalga Pass to Amchitka Pass": {
        "breakPointNumber": 25,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {"Pribilof Islands": True},
        "special": False,
        "states": ["Alaska"],
        "subregion": "Aleutian Islands",
    },
    "Amchitka Pass to Attu": {
        "breakPointNumber": 26,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alaska"],
        "subregion": "Aleutian Islands",
    },
    "San Francisco Bay": {
        "breakPointNumber": 75,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["California"],
    },
    "Suisun Bay": {
        "breakPointNumber": 76,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["California"],
    },
    "Grays Bay": {
        "breakPointNumber": 77,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "Puget Sound": {
        "breakPointNumber": 78,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "Island County": {
        "breakPointNumber": 79,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "Possession Sound": {
        "breakPointNumber": 80,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "Southern Strait of Juan de Fuca": {
        "breakPointNumber": 81,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "Northern Strait of Juan de Fuca": {
        "breakPointNumber": 82,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["British Columbia"],
    },
    "Western Skagit and Northwestern Snohomish Counties": {
        "breakPointNumber": 83,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "San Juan Islands": {
        "breakPointNumber": 84,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "Western Whatcom County": {
        "breakPointNumber": 85,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Washington"],
    },
    "Strait of Georgia": {
        "breakPointNumber": 86,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["British Columbia"],
    },
    "Lower Cook Inlet Region south of Kalgin Island": {
        "breakPointNumber": 87,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Northwest Kenai Peninsula": {
        "breakPointNumber": 88,
        "inclusionReferencePoints": {"City of Kenai": True},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Upper Cook Inlet": {
        "breakPointNumber": 89,
        "inclusionReferencePoints": {"Anchorage": True},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Pribilof Islands": {
        "breakPointNumber": 90,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Bristol Bay": {
        "breakPointNumber": 91,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {
            "Pribilof Islands": True,
            },
        "special": True,
        "states": ["Alaska"],
    },
    "Kuskokwim Delta Coast and Nunivak Island": {
        "breakPointNumber": 92,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Norton Sound/Saint Lawrence Island/Western AK Coast": {
        "breakPointNumber": 93,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Western AK from Cape Prince of Wales to Wainwright": {
        "breakPointNumber": 94,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Northern AK Border from Wainwright to the Canadian Border": {
        "breakPointNumber": 95,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": ["Alaska"],
    },
    "Brownsville to Baffin Bay": {
        "breakPointNumber": 100,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Texas"],
    },
    "Baffin Bay to Port OConnor": {
        "breakPointNumber": 101,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Texas"],
    },
    "Port OConnor to High Island": {
        "breakPointNumber": 102,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Texas"],
    },
    "High Island to Morgan City": {
        "breakPointNumber": 103,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Texas", "Louisiana"],
    },
    "Morgan City to The Miss./Alabama Border": {
        "breakPointNumber": 104,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Louisiana", "Mississippi"],
    },
    "The Miss./Alabama Border to Destin": {
        "breakPointNumber": 105,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Alabama", "Florida"],
    },
    "Destin to Suwannee River": {
        "breakPointNumber": 106,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Florida"],
    },
    "Suwannee River to Bonita Beach": {
        "breakPointNumber": 107,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Florida"],
    },
    "Bonita Beach to Flamingo": {
        "breakPointNumber": 108,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Florida"],
    },
    "Flamingo to Ocean Reef": {
        "breakPointNumber": 109,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Florida"],
    },
    "Ocean Reef to Jupiter Inlet": {
        "breakPointNumber": 110,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Florida"],
    },
    "Jupiter Inlet to Flagler Beach": {
        "breakPointNumber": 111,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Florida"],
    },
    "Flagler Beach to Altamaha Sound": {
        "breakPointNumber": 112,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Florida", "Georgia"],
    },
    "Altamaha Sound to South Santee River": {
        "breakPointNumber": 113,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Georgia", "South Carolina"],
    },
    "South Santee River to Surf City": {
        "breakPointNumber": 114,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["South Carolina", "North Carolina"],
    },
    "Surf City to Duck": {
        "breakPointNumber": 115,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["North Carolina"],
    },
    "Duck to New Point Comfort": {
        "breakPointNumber": 116,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["North Carolina", "Virginia"],
    },
    "New Point Comfort to Cape Henlopen": {
        "breakPointNumber": 117,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Virginia", "Maryland"],
    },
    "Cape Henlopen to Sandy Hook": {
        "breakPointNumber": 118,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Delaware", "New Jersey", "New York"],
    },
    "Sandy Hook to Watch Hill": {
        "breakPointNumber": 119,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["New York", "Connecticut"],
    },
    "Watch Hill to Merrimack River": {
        "breakPointNumber": 120,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Rhode Island", "Massachusetts"],
    },
    "Merrimack River to Stonington": {
        "breakPointNumber": 121,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["New Hampshire", "Maine"],
    },
    "Stonington to The US/Canada Border": {
        "breakPointNumber": 122,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Maine"],
    },
    "The US/Canada Border to Charlesville": {
        "breakPointNumber": 123,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["New Brunswick", "Nova Scotia"],
    },
    "Charlesville to Chezzetcook Inlet": {
        "breakPointNumber": 124,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Nova Scotia"],
    },
    "Chezzetcook Inlet to Meat Cove": {
        "breakPointNumber": 125,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Nova Scotia"],
    },
    "Meat Cove to Cape Ray": {
        "breakPointNumber": 126,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {"Gulf of Saint Lawrence": False},
        "special": False,
        "states": ["Nova Scotia", "Newfoundland and Labrador"],
    },
    "Cape Ray to La Manche": {
        "breakPointNumber": 127,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Newfoundland and Labrador"],
    },
    "La Manche to Strait of Belle Isle": {
        "breakPointNumber": 128,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Newfoundland and Labrador"],
    },
    "Strait of Belle Isle to Cape Chidley": {
        "breakPointNumber": 129,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Newfoundland and Labrador"],
    },
    "Gulf of Saint Lawrence": {
        "breakPointNumber": 180,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": True,
        "states": [""],
    },
    "Hawaii": {
        "breakPointNumber": 200,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Hawaii"],
    },
    "Maui": {
        "breakPointNumber": 201,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Hawaii"],
    },
    "Honolulu": {
        "breakPointNumber": 202,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Hawaii"],
    },
    "Kauai": {
        "breakPointNumber": 203,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Hawaii"],
    },
    "Guam": {
        "breakPointNumber": 300,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Guam"],
    },
    "American Samoa": {
        "breakPointNumber": 400,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["American Samoa"],
    },
    "Puerto Rico": {
        "breakPointNumber": 500,
        "inclusionReferencePoints": {},
        "inclusionSpecialProcedures": {},
        "special": False,
        "states": ["Puerto Rico"],
    },
}
